- name: Register hosts to ambari
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/hosts/{{ inventory_hostname }}"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: ''
    validate_certs: no
    status_code: 200,201,202
    return_content: yes
  register: register_node
  failed_when: register_node.status not in [409, 200, 201, 202]

- name: Register hosts to cluster
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/hosts"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: '[{"Hosts":{"host_name":"{{ inventory_hostname }}"}}]'
    body_format: json
    validate_certs: no
    status_code: 200,201,202
    return_content: yes
  register: register_hosts
  failed_when: register_hosts.status not in [409, 200, 201, 202]
